import Head from "next/head";
import OnlineStatus from "@Component/OnlineStatus";

function Home() {
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="card">
        <div className="card-header"></div>
        <div className="card-body">
          <div className="grid">
            <OnlineStatus />
          </div>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = function ({ req, res }) {
  return {
    props: {},
  };
};
export default Home;
